apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-notifier-system
  labels:
    app: alert-notifier-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-notifier-system
  template:
    metadata:
      labels:
        app: alert-notifier-system
    spec:
      containers:
        - name: alert-notifier-system
          image: alert-notifier-system:latest
          imagePullPolicy: Never
          env:
            - name: KAFKA_BROKER_URL
              value: "kafka:9092"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: user-manager-db-url
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: telegram-secrets
                  key: telegram-token
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "250m"
